// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12.04.2025, 21:46:40
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/user/Desktop/DevX/12/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX/12/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX/12/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX/12/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX/12/plugins/**/*.{js,ts,mjs}","C:/Users/user/Desktop/DevX/12/composables/**/*.{js,ts,mjs}","C:/Users/user/Desktop/DevX/12/utils/**/*.{js,ts,mjs}","C:/Users/user/Desktop/DevX/12/pages/faq.vue","C:/Users/user/Desktop/DevX/12/pages/about.vue","C:/Users/user/Desktop/DevX/12/pages/index.vue","C:/Users/user/Desktop/DevX/12/pages/contacts.vue","C:/Users/user/Desktop/DevX/12/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX/12/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX/12/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;